### PR TITLE
Added season colors and images

### PR DESCRIPTION
**Pull request by ErikS270102**
Sorry if i f'ed something up, I'm kinda new to GitHub. I've just found that having a bit more info on seasons is helpful, especially the images

### CODE REVIEW

**Comment by danielwerg** [comment]
You added all seasons (from 1 to 17), but `SEASONS` is made for `getRank` so it's should be from 6 to 17 since ubi lost data for older seasons.

And also you never used `color` and `image` values inside `getRank` only `name`.
What are you planning to use it for if this pr gets merged?

Can you link me where did you got image and colors for each season as well?

**Comment by ErikS270102** [comment]
Oh, I completely forgot about the `getRank` stuff. Also, i got the `image` and `color` from [here](https://www.ubisoft.com/en-us/game/rainbow-six/siege/game-info/seasons) (the color is just the css color of the season titles)

**Comment by ErikS270102** [comment]
I also used images from [here](https://liquipedia.net/rainbowsix/Portal:Weapons) to add `image` to `WEAPONS` constant and `getStats`

**Comment by ErikS270102** [comment]
> What are you planning to use it for if this pr gets merged?

I'm making an discord bot for me and some friends, and i have an /r6 command to get some stats and stuff. Having some Images in the discord embeds looks way better than just the text

**Comment by ErikS270102** [comment]
I have moved all the urls to the ubi cdn links. I have also moved the `SMG-12` to machine pistols since it is one

**Comment by danielwerg** [comment]
Little update, I didn't forget about this pr, but I will review and merge it only after I'm done with typescript rewrite.

How come gun what literally has "sub machine gun" in it's name is not sub machine gun 🤔

**Comment by ErikS270102** [comment]
I think ubi counts secondary "smgs" as mp. Their site says the smg-12 is an mp anyways

**Pull request merged**
