### PR TITLE
Add structural changes detection

### PR DESCRIPTION
**Pull request by EndBug**
This makes the action only update the file if there's a structural change (added/removed properties): this way it doesn't update the file every time there's a new push, only because the user has played in the meantime ;)

### CODE REVIEW

**Comment by EndBug** [comment]
@danielwerg There may be a problem with the secrets...

**Comment by danielwerg** [comment]
weird they should be working

**Comment by danielwerg** [comment]
Why don't we add "path" to action to begin with btw? So it will only run a job if there changes to `constants.js` or `getStats`.

**Comment by EndBug** [comment]
I think this way it's more maintainable: it will change based on the result, so if you decide to change the structure of the source code later in the development you won't need to worry about having to update this too.

**Comment by danielwerg** [comment]
I updated secrets, will see if that was a issue.

**Comment by danielwerg** [comment]
Yeah, it's something to do with pr.

**Comment by danielwerg** [comment]
@EndBug didn't it suppose to use secrets from your fork?

**Pull request merged**
